### ISSUE TITLE
Generated code for dde_solver

### ISSUE THREAD

**Issue by FabricioS** [WarrenWeckesser/vfgen#2]
First of all, thank you for this nice piece of software of vfgen !
However I have some troubles with the files generated by the dde_solver
command.
The *.f90 defines the *_ddes and *_history subroutines that have the
following declarations

```
SUBROUTINE modele1_nonneutre_ddes(t,x_,Zlags_,vf_)
! Arguments
DOUBLE PRECISION :: t
DOUBLE PRECISION, DIMENSION(NEQN) :: x_, vf_
DOUBLE PRECISION, DIMENSION(NEQN,NLAGS) :: Zlags_
...
SUBROUTINE modele1_nonneutre_history(t,x_)
DOUBLE PRECISION :: t
DOUBLE PRECISION, DIMENSION(NEQN) :: x_
INTENT(IN) :: t
INTENT(OUT) :: x_
...
```

gfortran has problem with it as DDE_SOLVER does not match any of the
possible DKL_ subroutine of the DDE_SOLVER interface (in
dde_solver_m.f90). So that it raises the following error:

```
modele1_nonneutre_demo.f90:64:6:
 SOL = DDE_SOLVER(NVAR, modele1_nonneutre_ddes, LAGS,modele1_nonneutre_history,TSPAN,OPTIONS=OPTS)
      1
Error: There is no specific function for the generic ‘dde_solver’ at (1)
```

This is confirmed by directly calling the expected DKL_\* subroutine in the demo :
    modele1_nonneutre_demo.f90:64:18:

```
 SOL = DKL_2(NVAR, modele1_nonneutre_ddes, LAGS,modele1_nonneutre_history,TSPAN,OPTIONS=OPTS)
                  1
Error: Interface mismatch in dummy procedure ‘ddes’ at (1): Shape mismatch in argument 'y'
```

Replacing the DIMENSION(NEQN) and DIMENSION(NEQN, NLAGS) by
DIMENSION(:) and DIMENSION(:,:), respectively, allows for the
compilation, but the program then segfaults.
Do you have any clues to solve that problem ?

**Comment by FabricioS** [comment]
Hi again,
It seems that the segfault is due to the interface of the *_ddes and *_history not being propagated inside the internals of dde_solver. It has the sad consequence of the shape of x_, Zlags_ and vf_ not being passed while calling these functions...
Should the dde_solver command of vfgen be consider as non functional ?

**Comment by rveltz** [comment]
Hi, 
Do you manage to compile the first example in [thompson](http://www.radford.edu/~thompson/ffddes/Files.html)? I stumble on the same mistake as you but the code is not generated by vfgen.

Thank you for your help,

Best regards

**Comment by uluzair** [comment]
Hi,
me too I am having this problem with the example from thompson. Did you solve it?
thx

**Comment by WarrenWeckesser** [comment]
Sorry for not addressing this issue for 16 months!  The code had worked in the past, as can be seen in the online documentation at http://www.warrenweckesser.net/vfgen/menu_dde_solver.html.  But I can reproduce the problem now, and I'm looking into it.

**Comment by WarrenWeckesser** [comment]
Newer versions of gfortran (i.e. 4.8.1 and later, as far as I know) require that the functions generated by vfgen use assumed-shape arrays to match the interfaces declared in the DDE_SOLVER code.  However, there is a problem with DDE_SOLVER itself.  It does not declare interfaces for arguments that are functions in all the places that it should.   Apparently, without the interface declarations, gfortran doesn't know that some of the arguments of the user's functions are assumed-shape, and it doesn't pass arguments to these functions correctly, leading to segmentation faults.

I'm looking into creating an updated version of DDE_SOLVER that has the necessary interface declarations.

**Comment by WarrenWeckesser** [comment]
I eventually did modify DDE_SOLVER, but I didn't update this issue...

There is a modified version of DDE_SOLVER at https://github.com/WarrenWeckesser/dde_solver that fixes some issues with the version that had been available from S. Thompson's web page.  That updated DDE_SOLVER_M works with the development version of VFGEN.
