### ISSUE TITLE
vfgen fails to build as it's looking for vf_help_text.cpp

### ISSUE THREAD

**Issue by sdwfrost** [WarrenWeckesser/vfgen#5]
The package fails to build as `vf_help_text.o` is listed in `OBJ_FILES` but there isn't a corresponding `.cpp` file in `vfgen/src`. Removing `vf_help_text.o` from `OBJ_FILES` allows compilation to continue, however, I then get the following error:

```
vfgen.o: In function `main':
vfgen.cpp:(.text.startup+0x3783): undefined reference to `VectorField::PrintBoostOdeint(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >)'
collect2: error: ld returned 1 exit status
Makefile.vfgen:53: recipe for target 'vfgen' failed
make: *** [vfgen] Error 1
```

This is on Ubuntu 18.04.

**Comment by WarrenWeckesser** [comment]
@sdwfrost, thanks for reporting the problem.  Back in May I made some changes to how the text for the help messages was stored.  I updated CMakeLists.txt to deal with the change (so building with CMake should work), but I neglected to updated Makefile.vfgen.  I'll take a closer look this weekend.

**Comment by sdwfrost** [comment]
Thanks @WarrenWeckesser! I have an example of using vfgen in my online textbook of epidemiological models [Epirecipes](http://epirecip.es/epicookbook/chapters/sir/vfgen), so fixing would be great as I'm more of a configure/make person than CMake...

**Comment by WarrenWeckesser** [comment]
@sdwfrost, I just pushed an update to the Makefiles.  If you are building from the github source, grab the latest version and let me know if you have any problems building vfgen.
