### ISSUE TITLE
suggestion to vectorize Functions

### ISSUE THREAD

**Issue by a-kramer** [WarrenWeckesser/vfgen#7]
Hello,
 I suggest to create a vector valued function that calculates all user defined Functions in one go, to not repeat unnecessary calculations (when all of them are needed), and most importantly: for convenience. 

Specifically, I would like that in the gsl_odeiv(2) module. To use the Function names _productively_, one could define an enum:

```C
enum Function_names {Name_1, Name_2}; /* etc */
```
and later on, in the unified output function:
```C
/*  User defined functions */
int SYSTEM_out(double t, const double y_[], void *params, double *Function)
{
 /* assignments 
  * and 
  * expression calculations 
  */
 Function[Name_1] = Value_1;
 Function[Name_2] = Value_2;
 /* etc. */
 return GSL_SUCCESS;
}
```
This function could also exist in _addition_ to the scalar functions. That would be neat, in most languages, I guess.
Thank you for all the hard work!

**Comment by WarrenWeckesser** [comment]
@a-kramer, (a belated) thanks for the suggestion!

This is certainly possible.  I've been doing some work on vfgen lately; I'll look into adding this.  It could be useful to have something like this in the other language/library outputs, too.

**Comment by WarrenWeckesser** [comment]
Only 2.5 years later, here you go: https://github.com/WarrenWeckesser/vfgen/commit/38c31a315d45dc5e8329ab8778260d9ba461935e.
